## This notebook is a guid for you to build an informative dataset for Quran Alphabet Numerals from below sources of digital quran
- Mushaf Al-Madinah from King Fahd for digital quran using Hafs Narration "https://dm.qurancomplex.gov.sa/"
- Quran Metadata from Tanzil project for digital Quran"https://tanzil.net/docs/"

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import xml.etree.ElementTree as ET
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mushaf-madinah/hafsData_v18.csv
/kaggle/input/mushaf-madinah/tanzil_quran_metadata.xml

## This data is taken from Mushaf Al-Madinah Hafs narration version 18 from King Fahad you can download data and fonts from here "https://qurancomplex.gov.sa/techquran/dev/" (Unicode Uthmanic Font (Hafs Narration))
### اخذ نص هذا المصحف من مصحف المدينة الرقمي الاصدار رقم 18 برواية حفص و يمكن تنزيله من الرابط اعلاه

In [2]:
mushaf_madinah = pd.read_csv('../input/mushaf-madinah/hafsData_v18.csv')
mushaf_madinah.head()
mushaf_madinah.info()
mushaf_madinah.rename(columns={'id':'aya_index'}, inplace= True)
mushaf_madinah.rename(columns={'aya_text_emlaey':'spoken_aya_text'}, inplace= True)
mushaf_madinah.rename(columns={'sora':'sura_mushaf_order'}, inplace= True)
mushaf_madinah.rename(columns={'sora_name_ar':'sura_name'}, inplace= True)
quran = mushaf_madinah

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6236 entries, 0 to 6235
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               6236 non-null   int64
 1   jozz             6236 non-null   int64
 2   sora             6236 non-null   int64
 3   sora_name_en     6236 non-null   object
 4   sora_name_ar     6236 non-null   object
 5   page             6236 non-null   int64
 6   line_start       6236 non-null   int64
 7   line_end         6236 non-null   int64
 8   aya_no           6236 non-null   int64
 9   aya_text         6236 non-null   object
 10  aya_text_emlaey  6236 non-null   object
dtypes: int64(7), object(4)
memory usage: 536.0+ KB

In [3]:
mushaf_madinah.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6236 entries, 0 to 6235
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   aya_index          6236 non-null   int64
 1   jozz               6236 non-null   int64
 2   sura_mushaf_order  6236 non-null   int64
 3   sora_name_en       6236 non-null   object
 4   sura_name          6236 non-null   object
 5   page               6236 non-null   int64
 6   line_start         6236 non-null   int64
 7   line_end           6236 non-null   int64
 8   aya_no             6236 non-null   int64
 9   aya_text           6236 non-null   object
 10  spoken_aya_text    6236 non-null   object
dtypes: int64(7), object(4)
memory usage: 536.0+ KB

In [4]:
mushaf_madinah.rename(columns={'id':'aya_index'}, inplace= True)
mushaf_madinah.rename(columns={'aya_text_emlaey':'spoken_aya_text'}, inplace= True)
mushaf_madinah.rename(columns={'sora':'sura_mushaf_order'}, inplace= True)
mushaf_madinah.rename(columns={'sora_name_ar':'sura_name'}, inplace= True)
quran = mushaf_madinah

## some Quran metadata from tanzil "https://tanzil.net/docs/"

In [5]:
tanzil_quran_metadata_root = ET.parse('../input/mushaf-madinah/tanzil_quran_metadata.xml').getroot()
suras = {}
for child in tanzil_quran_metadata_root.find('suras'):
    suras[int(child.attrib['index'])] = [child.attrib['order'], child.attrib['type']]
quran['sura_revel_order'] = quran['sura_mushaf_order'].apply(lambda x: int(suras[x][0]))
quran['sura_revel_place'] = quran['sura_mushaf_order'].apply(lambda x: 'مكية' if suras[x][1] == 'Meccan' else 'مدنية')

# Calculate Jomal (حساب الجُمّل Abjad numerals )
here some useful link "http://www.islamnoon.com/new/Derasat/Erhasat/e_hesab.htm"

In [6]:
quran_letters = {'ء','أ','إ','ا','ٱ','آ','ى','ب','ت','ث','ج','ح','خ','د','ذ','ر','ز','س','ش','ص','ض','ط','ظ','ع','غ','ف','ق','ك','ل','م','ن','ه','و','ؤ','ي','ئ'}
letter_jomal = {'ء': 1 ,'أ': 1 ,'إ': 1 ,'ا': 1 ,'ٱ': 1 ,'آ': 1 ,'ى': 1 ,'ب': 2 ,'ت': 400 ,'ة': 400 ,'ث': 500 ,'ج': 3 ,'ح': 8 ,'خ': 600 ,'د': 4 ,'ذ': 700 ,'ر': 200 ,'ز': 7 ,'س': 60 ,'ش': 300 ,'ص': 90 ,'ض': 800 ,'ط': 9 ,'ظ': 900 ,'ع': 70 ,'غ': 1000 ,'ف': 80 ,'ق': 100 ,'ك': 20 ,'ل': 30 ,'م': 40 ,'ن': 50 ,'ه': 5 ,'و': 6 ,'ؤ': 6 ,'ي': 10 ,'ئ': 10}

def get_aya_words(aya):
    aya = aya.split()[:-1]
    if aya[0] == '۞':
        aya = aya[1:]
    if aya[-1][-1] == '۩':
        aya[-1] = aya[-1][:-1]
    return aya

def get_letters(text):
    letters = []
    for words in text.split():
        for c in words:
            if c in quran_letters:
                letters.append(c)
    return letters

def get_invariant_letters(text):
    letters = []
    for words in text.split():
        for c in words:
            if c in quran_letters:
                if c in ['ء','آ','أ','إ','ا','ى','ٱ']:
                    letters.append('ا')
                elif c in ['ة','ت',]:
                    letters.append('ت')
                elif c in ['ؤ','و']:
                    letters.append('و')
                elif c in ['ئ','ي']:
                    letters.append('ي')
                else:
                    letters.append(c)
    return letters

def calculate_text_jomal(text):
    total = 0
    for c in get_letters(text):
        total += letter_jomal[c]
    return total
    
def calculate_letters_jomal(letters):
    total = 0
    for c in letters:
        total += letter_jomal[c]
    return total

def calculate_cumulative_sum(number):
    total = 0
    for n in range(number + 1):
        total += n
    return total

def get_aya_indexes_list(aya):
    pass

# Sura Name Feature

In [7]:
quran['sura_cumulative_mushaf_order'] = quran['sura_mushaf_order'].apply(lambda order: calculate_cumulative_sum(order))
quran['sura_cumulative_revel_order'] = quran['sura_revel_order'].apply(lambda order: calculate_cumulative_sum(order))
quran['sura_name_letters'] = quran['sura_name'].apply(lambda name: get_letters(name))
quran['sura_name_letters_count'] = quran['sura_name_letters'].apply(lambda letters: len(letters))
quran['invariant_sura_name_letters'] = quran['sura_name'].apply(lambda name: get_invariant_letters(name))
quran['sura_name_invariant_letters_count'] = quran['invariant_sura_name_letters'].apply(lambda letters: len(letters))
quran['sura_name_jomal'] = quran['sura_name_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['sura_name_cumulative_jomal'] = quran['sura_name_jomal'].cumsum()
quran['sura_name_unique_letters'] = quran['sura_name_letters'].apply(lambda letters: set(letters))
quran['sura_name_unique_letters_count'] = quran['sura_name_unique_letters'].apply(lambda letters: len(letters))
quran['sura_name_unique_invariant_letters'] = quran['invariant_sura_name_letters'].apply(lambda letters: set(letters))
quran['sura_name_unique_invariant_letters_count'] = quran['sura_name_unique_invariant_letters'].apply(lambda letters: len(letters))
quran['sura_name_unique_letters_jomal'] = quran['sura_name_unique_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['sura_name_unique_letters_cumulative_jomal'] = quran['sura_name_unique_letters_jomal'].cumsum()
quran.head(10)[['sura_cumulative_mushaf_order','sura_cumulative_revel_order','sura_name_letters',\
    'sura_name_letters_count','invariant_sura_name_letters','sura_name_invariant_letters_count',\
        'sura_name_jomal','sura_name_cumulative_jomal','sura_name_unique_letters',\
            'sura_name_unique_letters_count','sura_name_unique_invariant_letters',\
                'sura_name_unique_invariant_letters_count','sura_name_unique_letters_jomal',\
                    'sura_name_unique_letters_cumulative_jomal']]

,sura_cumulative_mushaf_order,sura_cumulative_revel_order,sura_name_letters,sura_name_letters_count,invariant_sura_name_letters,sura_name_invariant_letters_count,sura_name_jomal,sura_name_cumulative_jomal,sura_name_unique_letters,sura_name_unique_letters_count,sura_name_unique_invariant_letters,sura_name_unique_invariant_letters_count,sura_name_unique_letters_jomal,sura_name_unique_letters_cumulative_jomal
0,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,520,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,519
1,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,1040,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,1038
2,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,1560,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,1557
3,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,2080,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,2076
4,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,2600,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,2595
5,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,3120,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,3114
6,1,15,"[ا, ل, ف, ا, ت, ح]",6,"[ا, ل, ف, ا, ت, ح]",6,520,3640,"{ا, ل, ح, ف, ت}",5,"{ا, ل, ح, ف, ت}",5,519,3633
7,3,3828,"[ا, ل, ب, ق, ر]",5,"[ا, ل, ب, ق, ر]",5,333,3973,"{ب, ا, ق, ر, ل}",5,"{ب, ا, ق, ر, ل}",5,333,3966
8,3,3828,"[ا, ل, ب, ق, ر]",5,"[ا, ل, ب, ق, ر]",5,333,4306,"{ب, ا, ق, ر, ل}",5,"{ب, ا, ق, ر, ل}",5,333,4299
9,3,3828,"[ا, ل, ب, ق, ر]",5,"[ا, ل, ب, ق, ر]",5,333,4639,"{ب, ا, ق, ر, ل}",5,"{ب, ا, ق, ر, ل}",5,333,4632

# written (uthmani) text features

In [8]:
quran['aya_words'] = quran['aya_text'].apply(lambda x : get_aya_words(x))
quran['aya_words_count'] = quran['aya_words'].apply(lambda words: len(words))
quran['aya_letters'] = quran['aya_text'].apply(lambda aya: get_letters(aya))
quran['aya_letters_count'] = quran['aya_letters'].apply(lambda letters: len(letters))
quran['aya_invariant_letters'] = quran['aya_text'].apply(lambda letters: get_invariant_letters(letters))
quran['aya_invariant_letters_count'] = quran['aya_invariant_letters'].apply(lambda letters: len(letters))
quran['aya_jomal'] = quran['aya_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['aya_cumulative_jomal'] = quran['aya_jomal'].cumsum()
quran['aya_unique_letters'] = quran['aya_letters'].apply(lambda letters: set(letters))
quran['aya_unique_letters_count'] = quran['aya_unique_letters'].apply(lambda letters: len(letters))
quran['aya_unique_invariant_letters'] = quran['aya_invariant_letters'].apply(lambda letters: set(letters))
quran['aya_unique_invariant_letters_count'] = quran['aya_unique_invariant_letters'].apply(lambda letters: len(letters))
quran['aya_unique_letters_jomal'] = quran['aya_unique_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['aya_unique_letters_commulative_jomal'] = quran['aya_unique_letters_jomal'].cumsum()
quran.head(10)[['aya_words','aya_words_count','aya_letters','aya_letters_count','aya_invariant_letters',\
    'aya_invariant_letters_count','aya_jomal','aya_cumulative_jomal','aya_unique_letters',\
        'aya_unique_letters_count','aya_unique_invariant_letters','aya_unique_invariant_letters_count',\
            'aya_unique_letters_jomal','aya_unique_letters_commulative_jomal']]

,aya_words,aya_words_count,aya_letters,aya_letters_count,aya_invariant_letters,aya_invariant_letters_count,aya_jomal,aya_cumulative_jomal,aya_unique_letters,aya_unique_letters_count,aya_unique_invariant_letters,aya_unique_invariant_letters_count,aya_unique_letters_jomal,aya_unique_letters_commulative_jomal
0,"[بِسۡمِ, ٱللَّهِ, ٱلرَّحۡمَٰنِ, ٱلرَّحِيمِ]",4,"[ب, س, م, ٱ, ل, ل, ه, ٱ, ل, ر, ح, م, ن, ٱ, ل, ...",19,"[ب, س, م, ا, ل, ل, ه, ا, ل, ر, ح, م, ن, ا, ل, ...",19,786,786,"{م, ب, ي, ه, ل, ر, ح, ٱ, س, ن}",10,"{م, ب, ا, ي, ه, ل, ر, ح, س, ن}",10,406,406
1,"[ٱلۡحَمۡدُ, لِلَّهِ, رَبِّ, ٱلۡعَٰلَمِينَ]",4,"[ٱ, ل, ح, م, د, ل, ل, ه, ر, ب, ٱ, ل, ع, ل, م, ...",17,"[ا, ل, ح, م, د, ل, ل, ه, ر, ب, ا, ل, ع, ل, م, ...",17,581,1367,"{م, ب, ي, ه, ل, ر, ع, ح, ٱ, د, ن}",11,"{م, ب, ا, ي, ه, ل, ر, ع, ح, د, ن}",11,420,826
2,"[ٱلرَّحۡمَٰنِ, ٱلرَّحِيمِ]",2,"[ٱ, ل, ر, ح, م, ن, ٱ, ل, ر, ح, ي, م]",12,"[ا, ل, ر, ح, م, ن, ا, ل, ر, ح, ي, م]",12,618,1985,"{م, ي, ل, ر, ح, ٱ, ن}",7,"{م, ا, ي, ر, ل, ح, ن}",7,339,1165
3,"[مَٰلِكِ, يَوۡمِ, ٱلدِّينِ]",3,"[م, ل, ك, ي, و, م, ٱ, ل, د, ي, ن]",11,"[م, ل, ك, ي, و, م, ا, ل, د, ي, ن]",11,241,2226,"{م, ي, ل, ٱ, ن, د, ك, و}",8,"{م, ا, ي, ل, ن, د, ك, و}",8,161,1326
4,"[إِيَّاكَ, نَعۡبُدُ, وَإِيَّاكَ, نَسۡتَعِينُ]",4,"[إ, ي, ا, ك, ن, ع, ب, د, و, إ, ي, ا, ك, ن, س, ...",19,"[ا, ي, ا, ك, ن, ع, ب, د, و, ا, ي, ا, ك, ن, س, ...",19,836,3062,"{ب, ا, ي, إ, ع, س, ت, و, د, ك, ن}",11,"{ب, ا, ي, ع, س, ت, و, د, ك, ن}",10,624,1950
5,"[ٱهۡدِنَا, ٱلصِّرَٰطَ, ٱلۡمُسۡتَقِيمَ]",3,"[ٱ, ه, د, ن, ا, ٱ, ل, ص, ر, ط, ٱ, ل, م, س, ت, ...",18,"[ا, ه, د, ن, ا, ا, ل, ص, ر, ط, ا, ل, م, س, ت, ...",18,1072,4134,"{م, ا, ي, ص, ه, ل, ر, ط, ق, ٱ, س, ت, د, ن}",14,"{م, ا, ي, ص, ه, ل, ر, ط, ق, س, ت, د, ن}",13,1000,2950
6,"[صِرَٰطَ, ٱلَّذِينَ, أَنۡعَمۡتَ, عَلَيۡهِمۡ, غ...",9,"[ص, ر, ط, ٱ, ل, ذ, ي, ن, أ, ن, ع, م, ت, ع, ل, ...",43,"[ص, ر, ط, ا, ل, ذ, ي, ن, ا, ن, ع, م, ت, ع, ل, ...",43,6009,10143,"{م, ذ, ض, ب, ا, غ, ي, ص, ع, ل, ر, ط, ه, ٱ, أ, ...",18,"{م, ذ, ا, ض, ب, غ, ي, ص, ع, ل, ر, ط, ه, ت, و, ن}",16,3415,6365
7,[الٓمٓ],1,"[ا, ل, م]",3,"[ا, ل, م]",3,71,10214,"{م, ل, ا}",3,"{م, ل, ا}",3,71,6436
8,"[ذَٰلِكَ, ٱلۡكِتَٰبُ, لَا, رَيۡبَۛ, فِيهِۛ, هُ...",7,"[ذ, ل, ك, ٱ, ل, ك, ت, ب, ل, ا, ر, ي, ب, ف, ي, ...",26,"[ذ, ل, ك, ا, ل, ك, ت, ب, ل, ا, ر, ي, ب, ف, ي, ...",26,2211,12425,"{ب, ذ, ا, م, ي, ه, ل, ر, ق, ف, ٱ, ت, ى, د, ك, ن}",16,"{ب, ذ, ا, م, ي, ه, ل, ر, ق, ف, ت, د, ك, ن}",14,1644,8080
9,"[ٱلَّذِينَ, يُؤۡمِنُونَ, بِٱلۡغَيۡبِ, وَيُقِيم...",8,"[ٱ, ل, ذ, ي, ن, ي, ؤ, م, ن, و, ن, ب, ٱ, ل, غ, ...",45,"[ا, ل, ذ, ي, ن, ي, و, م, ن, و, ن, ب, ا, ل, غ, ...",45,3162,15587,"{م, ذ, ب, ا, ي, ص, ز, ق, ل, ؤ, ر, ه, ٱ, ف, غ, ...",17,"{م, ذ, ا, ب, ي, ص, ز, ق, ل, ر, ه, ف, غ, و, ن}",15,2328,10408

# spoken text (Note: text as what it sounds) features

In [9]:
quran['spoken_aya_words'] = quran['spoken_aya_text'].str.split()
quran['spoken_aya_words_count'] = quran['spoken_aya_words'].apply(lambda words: len(words))
quran['spoken_aya_letters'] = quran['spoken_aya_text'].apply(lambda aya: get_letters(aya))
quran['spoken_aya_letters_count'] = quran['spoken_aya_letters'].apply(lambda letters: len(letters))
quran['spoken_aya_invariant_letters'] = quran['spoken_aya_text'].apply(lambda letters: get_invariant_letters(letters))
quran['spoken_aya_invariant_letters_count'] = quran['spoken_aya_invariant_letters'].apply(lambda letters: len(letters))
quran['spoken_aya_jomal'] = quran['spoken_aya_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['spoken_aya_cumulative_jomal'] = quran['spoken_aya_jomal'].cumsum()
quran['spoken_aya_unique_letters'] = quran['spoken_aya_letters'].apply(lambda letters: set(letters))
quran['spoken_aya_unique_letters_count'] = quran['spoken_aya_unique_letters'].apply(lambda letters: len(letters))
quran['spoken_aya_unique_invariant_letters'] = quran['spoken_aya_invariant_letters'].apply(lambda letters: set(letters))
quran['spoken_aya_unique_invariant_letters_count'] = quran['spoken_aya_unique_invariant_letters'].apply(lambda letters: len(letters))
quran['spoken_aya_unique_letters_jomal'] = quran['spoken_aya_unique_letters'].apply(lambda letters: calculate_letters_jomal(letters))
quran['spoken_aya_unique_letters_commulative_jomal'] = quran['spoken_aya_unique_letters_jomal'].cumsum()
quran.head(10)[['spoken_aya_words','spoken_aya_words_count','spoken_aya_letters','spoken_aya_letters_count',\
    'spoken_aya_invariant_letters','spoken_aya_invariant_letters_count','spoken_aya_jomal',\
        'spoken_aya_cumulative_jomal','spoken_aya_unique_letters','spoken_aya_unique_letters_count',\
            'spoken_aya_unique_invariant_letters','spoken_aya_unique_invariant_letters_count',\
                'spoken_aya_unique_letters_jomal','spoken_aya_unique_letters_commulative_jomal']]

,spoken_aya_words,spoken_aya_words_count,spoken_aya_letters,spoken_aya_letters_count,spoken_aya_invariant_letters,spoken_aya_invariant_letters_count,spoken_aya_jomal,spoken_aya_cumulative_jomal,spoken_aya_unique_letters,spoken_aya_unique_letters_count,spoken_aya_unique_invariant_letters,spoken_aya_unique_invariant_letters_count,spoken_aya_unique_letters_jomal,spoken_aya_unique_letters_commulative_jomal
0,"[بسم, الله, الرحمن, الرحيم]",4,"[ب, س, م, ا, ل, ل, ه, ا, ل, ر, ح, م, ن, ا, ل, ...",19,"[ب, س, م, ا, ل, ل, ه, ا, ل, ر, ح, م, ن, ا, ل, ...",19,786,786,"{م, ب, ا, ي, ه, ل, ر, ح, س, ن}",10,"{م, ب, ا, ي, ه, ل, ر, ح, س, ن}",10,406,406
1,"[الحمد, لله, رب, العالمين]",4,"[ا, ل, ح, م, د, ل, ل, ه, ر, ب, ا, ل, ع, ا, ل, ...",18,"[ا, ل, ح, م, د, ل, ل, ه, ر, ب, ا, ل, ع, ا, ل, ...",18,582,1368,"{م, ب, ا, ي, ه, ل, ر, ع, ح, د, ن}",11,"{م, ب, ا, ي, ه, ل, ر, ع, ح, د, ن}",11,420,826
2,"[الرحمن, الرحيم]",2,"[ا, ل, ر, ح, م, ن, ا, ل, ر, ح, ي, م]",12,"[ا, ل, ر, ح, م, ن, ا, ل, ر, ح, ي, م]",12,618,1986,"{م, ا, ي, ر, ل, ح, ن}",7,"{م, ا, ي, ر, ل, ح, ن}",7,339,1165
3,"[مالك, يوم, الدين]",3,"[م, ا, ل, ك, ي, و, م, ا, ل, د, ي, ن]",12,"[م, ا, ل, ك, ي, و, م, ا, ل, د, ي, ن]",12,242,2228,"{م, ا, ي, ل, ن, د, ك, و}",8,"{م, ا, ي, ل, ن, د, ك, و}",8,161,1326
4,"[إياك, نعبد, وإياك, نستعين]",4,"[إ, ي, ا, ك, ن, ع, ب, د, و, إ, ي, ا, ك, ن, س, ...",19,"[ا, ي, ا, ك, ن, ع, ب, د, و, ا, ي, ا, ك, ن, س, ...",19,836,3064,"{ب, ا, ي, إ, ع, س, ت, و, د, ك, ن}",11,"{ب, ا, ي, ع, س, ت, و, د, ك, ن}",10,624,1950
5,"[اهدنا, الصراط, المستقيم]",3,"[ا, ه, د, ن, ا, ا, ل, ص, ر, ا, ط, ا, ل, م, س, ...",19,"[ا, ه, د, ن, ا, ا, ل, ص, ر, ا, ط, ا, ل, م, س, ...",19,1073,4137,"{م, ا, ي, ص, ه, ل, ر, ط, ق, س, ت, د, ن}",13,"{م, ا, ي, ص, ه, ل, ر, ط, ق, س, ت, د, ن}",13,999,2949
6,"[صراط, الذين, أنعمت, عليهم, غير, المغضوب, عليه...",9,"[ص, ر, ا, ط, ا, ل, ذ, ي, ن, أ, ن, ع, م, ت, ع, ...",44,"[ص, ر, ا, ط, ا, ل, ذ, ي, ن, ا, ن, ع, م, ت, ع, ...",44,6010,10147,"{م, ذ, ا, ض, ب, غ, ي, ص, ع, ر, ل, ط, ه, أ, ت, ...",17,"{م, ذ, ا, ض, ب, غ, ي, ص, ع, ر, ل, ط, ه, ت, و, ن}",16,3414,6363
7,[الم],1,"[ا, ل, م]",3,"[ا, ل, م]",3,71,10218,"{م, ل, ا}",3,"{م, ل, ا}",3,71,6434
8,"[ذلك, الكتاب, لا, ريب, فيه, هدى, للمتقين]",7,"[ذ, ل, ك, ا, ل, ك, ت, ا, ب, ل, ا, ر, ي, ب, ف, ...",27,"[ذ, ل, ك, ا, ل, ك, ت, ا, ب, ل, ا, ر, ي, ب, ف, ...",27,2212,12430,"{ب, ذ, ا, م, ي, ه, ل, ر, ق, ف, ت, ى, د, ك, ن}",15,"{ب, ذ, ا, م, ي, ه, ل, ر, ق, ف, ت, د, ك, ن}",14,1643,8077
9,"[الذين, يؤمنون, بالغيب, ويقيمون, الصلاة, ومما,...",8,"[ا, ل, ذ, ي, ن, ي, ؤ, م, ن, و, ن, ب, ا, ل, غ, ...",46,"[ا, ل, ذ, ي, ن, ي, و, م, ن, و, ن, ب, ا, ل, غ, ...",46,3158,15588,"{م, ذ, ا, ب, ي, ص, ز, ق, ل, ؤ, ر, ه, ف, غ, و, ن}",16,"{م, ذ, ا, ب, ي, ص, ز, ق, ل, ر, ه, ف, غ, و, ن}",15,2327,10404

# Fix some spaces issues
### fix spaces in aya of spoken text

In [10]:
# get un matched words counts between written and spoken text
words_to_fix = quran[(quran['spoken_aya_words_count'] != quran['aya_words_count'])]['spoken_aya_words']
len(words_to_fix)

61

In [11]:
words_to_fix.iloc[0][0:2] = [''.join(words_to_fix.iloc[0][0:2])]
words_to_fix.iloc[1][0:2] = [''.join(words_to_fix.iloc[1][0:2])]
words_to_fix.iloc[2][14:16] = [''.join(words_to_fix.iloc[2][14:16])]
words_to_fix.iloc[3][9:11] = [''.join(words_to_fix.iloc[3][9:11])]
words_to_fix.iloc[4][0:2] = [''.join(words_to_fix.iloc[4][0:2])]
words_to_fix.iloc[5][0:2] = [''.join(words_to_fix.iloc[5][0:2])]
words_to_fix.iloc[6][0:2] = [''.join(words_to_fix.iloc[6][0:2])]
words_to_fix.iloc[7][0:2] = [''.join(words_to_fix.iloc[7][0:2])]
words_to_fix.iloc[8][16:18] = [''.join(words_to_fix.iloc[8][16:18])]
words_to_fix.iloc[9][0:2] = [''.join(words_to_fix.iloc[9][0:2])]
words_to_fix.iloc[10][0:2] = [''.join(words_to_fix.iloc[10][0:2])]
words_to_fix.iloc[11][0:2] = [''.join(words_to_fix.iloc[11][0:2])]
words_to_fix.iloc[12][-4:-2] = [''.join(words_to_fix.iloc[12][-4:-2])]
words_to_fix.iloc[13][0:2] = [''.join(words_to_fix.iloc[13][0:2])]
words_to_fix.iloc[14][0:2] = [''.join(words_to_fix.iloc[14][0:2])]
words_to_fix.iloc[15][0:2] = [''.join(words_to_fix.iloc[15][0:2])]
words_to_fix.iloc[16][0:2] = [''.join(words_to_fix.iloc[16][0:2])]
words_to_fix.iloc[17][0:2] = [''.join(words_to_fix.iloc[17][0:2])]
words_to_fix.iloc[18][0:2] = [''.join(words_to_fix.iloc[18][0:2])]
words_to_fix.iloc[19][17:19] = [''.join(words_to_fix.iloc[19][17:19])]
words_to_fix.iloc[20][0:2] = [''.join(words_to_fix.iloc[20][0:2])]
words_to_fix.iloc[21][1:3] = [''.join(words_to_fix.iloc[21][1:3])]
words_to_fix.iloc[22][0:2] = [''.join(words_to_fix.iloc[22][0:2])]
words_to_fix.iloc[23][0:2] = [''.join(words_to_fix.iloc[23][0:2])]
words_to_fix.iloc[24][0:2] = [''.join(words_to_fix.iloc[24][0:2])]
words_to_fix.iloc[25][6:8] = [''.join(words_to_fix.iloc[25][6:8])]
words_to_fix.iloc[26][0:2] = [''.join(words_to_fix.iloc[26][0:2])]
words_to_fix.iloc[27][0:2] = [''.join(words_to_fix.iloc[27][0:2])]
words_to_fix.iloc[28][1:3] = [''.join(words_to_fix.iloc[28][1:3])]
words_to_fix.iloc[29][1:3] = [''.join(words_to_fix.iloc[29][1:3])]
words_to_fix.iloc[30][3:5] = [''.join(words_to_fix.iloc[30][3:5])]
words_to_fix.iloc[31][12:14] = [''.join(words_to_fix.iloc[31][12:14])]
words_to_fix.iloc[32][8:10] = [''.join(words_to_fix.iloc[32][8:10])]
words_to_fix.iloc[33][6:8] = [''.join(words_to_fix.iloc[33][6:8])]
words_to_fix.iloc[34][24:26] = [''.join(words_to_fix.iloc[34][24:26])]
words_to_fix.iloc[35][0:2] = [''.join(words_to_fix.iloc[35][0:2])]
words_to_fix.iloc[36][0:2] = [''.join(words_to_fix.iloc[36][0:2])]
words_to_fix.iloc[37][0:2] = [''.join(words_to_fix.iloc[37][0:2])]
words_to_fix.iloc[38][0:2] = [''.join(words_to_fix.iloc[38][0:2])]
words_to_fix.iloc[39][0:2] = [''.join(words_to_fix.iloc[39][0:2])]
words_to_fix.iloc[40][0:2] = [''.join(words_to_fix.iloc[40][0:2])]
words_to_fix.iloc[41][0:2] = [''.join(words_to_fix.iloc[41][0:2])]
words_to_fix.iloc[42][0:2] = [''.join(words_to_fix.iloc[42][0:2])]
words_to_fix.iloc[43][11:13] = [''.join(words_to_fix.iloc[43][11:13])]
words_to_fix.iloc[44][0:2] = [''.join(words_to_fix.iloc[44][0:2])]
words_to_fix.iloc[45][0:2] = [''.join(words_to_fix.iloc[45][0:2])]
words_to_fix.iloc[46][0:2] = [''.join(words_to_fix.iloc[46][0:2])]
words_to_fix.iloc[47][0:2] = [''.join(words_to_fix.iloc[47][0:2])]
words_to_fix.iloc[48][0:2] = [''.join(words_to_fix.iloc[48][0:2])]
words_to_fix.iloc[49][0:2] = [''.join(words_to_fix.iloc[49][0:2])]
words_to_fix.iloc[50][7:9] = [''.join(words_to_fix.iloc[50][7:9])]
words_to_fix.iloc[51][0:2] = [''.join(words_to_fix.iloc[51][0:2])]
words_to_fix.iloc[52][0:2] = [''.join(words_to_fix.iloc[52][0:2])]
words_to_fix.iloc[53][1:3] = [''.join(words_to_fix.iloc[53][1:3])]
words_to_fix.iloc[54][12:14] = [''.join(words_to_fix.iloc[54][12:14])]
words_to_fix.iloc[55][11:13] = [''.join(words_to_fix.iloc[55][11:13])]
words_to_fix.iloc[56][0:2] = [''.join(words_to_fix.iloc[56][0:2])]
words_to_fix.iloc[57][1:3] = [''.join(words_to_fix.iloc[57][1:3])]
words_to_fix.iloc[58][0:2] = [''.join(words_to_fix.iloc[58][0:2])]
words_to_fix.iloc[59][0:2] = [''.join(words_to_fix.iloc[59][0:2])]
words_to_fix.iloc[60][0:2] = [''.join(words_to_fix.iloc[60][0:2])]

In [12]:
#recalculate words counts
quran['spoken_aya_words_count'] = quran['spoken_aya_words'].apply(lambda x: len(x))

In [13]:
#check if there is any unmatched ayas left
len(quran[(quran['spoken_aya_words_count'] != quran['aya_words_count'])]['spoken_aya_words'])

0

# save our dataset to new files
### rearrange columns

In [14]:
quran = quran [[\
'sura_name',\
'sura_mushaf_order',\
'sura_revel_order',\
'sura_revel_place',\
'sura_cumulative_mushaf_order',\
'sura_cumulative_revel_order',\
'sura_name_letters',\
'sura_name_letters_count',\
'invariant_sura_name_letters',\
'sura_name_invariant_letters_count',\
'sura_name_jomal',\
'sura_name_cumulative_jomal',\
'sura_name_unique_letters',\
'sura_name_unique_letters_count',\
'sura_name_unique_invariant_letters',\
'sura_name_unique_invariant_letters_count',\
'sura_name_unique_letters_jomal',\
'sura_name_unique_letters_cumulative_jomal',\
'aya_index',\
'aya_no',\
'aya_text',\
'aya_words',\
'aya_words_count',\
'aya_letters',\
'aya_letters_count',\
'aya_invariant_letters',\
'aya_invariant_letters_count',\
'aya_jomal',\
'aya_cumulative_jomal',\
'aya_unique_letters',\
'aya_unique_letters_count',\
'aya_unique_invariant_letters',\
'aya_unique_invariant_letters_count',\
'aya_unique_letters_jomal',\
'aya_unique_letters_commulative_jomal',\
'spoken_aya_text',\
'spoken_aya_words',\
'spoken_aya_words_count',\
'spoken_aya_letters',\
'spoken_aya_letters_count',\
'spoken_aya_invariant_letters',\
'spoken_aya_invariant_letters_count',\
'spoken_aya_jomal',\
'spoken_aya_cumulative_jomal',\
'spoken_aya_unique_letters',\
'spoken_aya_unique_letters_count',\
'spoken_aya_unique_invariant_letters',\
'spoken_aya_unique_invariant_letters_count',\
'spoken_aya_unique_letters_jomal',\
'spoken_aya_unique_letters_commulative_jomal'\
    ]]
quran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6236 entries, 0 to 6235
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   sura_name                                    6236 non-null   object
 1   sura_mushaf_order                            6236 non-null   int64
 2   sura_revel_order                             6236 non-null   int64
 3   sura_revel_place                             6236 non-null   object
 4   sura_cumulative_mushaf_order                 6236 non-null   int64
 5   sura_cumulative_revel_order                  6236 non-null   int64
 6   sura_name_letters                            6236 non-null   object
 7   sura_name_letters_count                      6236 non-null   int64
 8   invariant_sura_name_letters                  6236 non-null   object
 9   sura_name_invariant_letters_count            6236 non-null   int64
 10  sura_name_jomal                              6236 non-null   int64
 11  sura_name_cumulative_jomal                   6236 non-null   int64
 12  sura_name_unique_letters                     6236 non-null   object
 13  sura_name_unique_letters_count               6236 non-null   int64
 14  sura_name_unique_invariant_letters           6236 non-null   object
 15  sura_name_unique_invariant_letters_count     6236 non-null   int64
 16  sura_name_unique_letters_jomal               6236 non-null   int64
 17  sura_name_unique_letters_cumulative_jomal    6236 non-null   int64
 18  aya_index                                    6236 non-null   int64
 19  aya_no                                       6236 non-null   int64
 20  aya_text                                     6236 non-null   object
 21  aya_words                                    6236 non-null   object
 22  aya_words_count                              6236 non-null   int64
 23  aya_letters                                  6236 non-null   object
 24  aya_letters_count                            6236 non-null   int64
 25  aya_invariant_letters                        6236 non-null   object
 26  aya_invariant_letters_count                  6236 non-null   int64
 27  aya_jomal                                    6236 non-null   int64
 28  aya_cumulative_jomal                         6236 non-null   int64
 29  aya_unique_letters                           6236 non-null   object
 30  aya_unique_letters_count                     6236 non-null   int64
 31  aya_unique_invariant_letters                 6236 non-null   object
 32  aya_unique_invariant_letters_count           6236 non-null   int64
 33  aya_unique_letters_jomal                     6236 non-null   int64
 34  aya_unique_letters_commulative_jomal         6236 non-null   int64
 35  spoken_aya_text                              6236 non-null   object
 36  spoken_aya_words                             6236 non-null   object
 37  spoken_aya_words_count                       6236 non-null   int64
 38  spoken_aya_letters                           6236 non-null   object
 39  spoken_aya_letters_count                     6236 non-null   int64
 40  spoken_aya_invariant_letters                 6236 non-null   object
 41  spoken_aya_invariant_letters_count           6236 non-null   int64
 42  spoken_aya_jomal                             6236 non-null   int64
 43  spoken_aya_cumulative_jomal                  6236 non-null   int64
 44  spoken_aya_unique_letters                    6236 non-null   object
 45  spoken_aya_unique_letters_count              6236 non-null   int64
 46  spoken_aya_unique_invariant_letters          6236 non-null   object
 47  spoken_aya_unique_invariant_letters_count    6236 non-null   int64
 48  spoken_aya_unique_letters_jomal              6236 non-null   int64
 49  spoken_aya_unique_letters_commulative_jomal  6236 non-null   int64
dtypes: int64(32), object(18)
memory usage: 2.4+ MB

### Save Dataset